swagger: "2.0"
info:
  title: Bookshop API
  description: You can get an individual book or search for books by title, author and/or publisher. 
  version: 1.0.0
schemes:
  - http
host: localhost:8000
basePath: /booksforall.com/v1
paths:
  /bookstore/book:
    post:
      summary: Add a new book 
      parameters:
        - name: title
          in: query
          required: true
          type: string
        - name: author
          in: query
          required: true
          type: string
        - name: publisher
          in: query
          required: true
          type: string
      responses:
        200:
          description: Success
  /bookstore/{id}:
    get:
      summary: Get a book by id 
      parameters:
        - name: id
          in: path
          description: The id of the book.
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Success
          examples:
            application/json: |-
              {
                "title": "How to Avoid Huge Ships", 
                "author": "Captain John W. Trimmer",
                "publisher": "Cornell Maritime Press"
              }
  /bookstore/booksearch:
    get:
      summary: Search for a book 
      parameters:
        - name: title
          in: query
          required: false
          type: string
        - name: author
          in: query
          required: false
          type: string
        - name: publisher
          in: query
          required: false
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Success
          examples:
            application/json: |-
              {
                "title": "How to Avoid Huge Ships", 
                "author": "Captain John W. Trimmer",
                "publisher": "Cornell Maritime Press"
              }
